### PR TITLE
[Fix] : added warning to manage event page

### LINKED ISSUE #8964: [BUG] manage event page isn't showing no events warning.
### Description

Go to https://www.biodrop.io/account/manage/events
When there are zero events it should show no Events and the filter icon should be hidden if there are no events to display.

### Screenshots

image
It should have a warning message like
image

### Do you want to work on this issue?

None

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by adarshmalviya12**
## Fixes Issue

closes #8964

## Changes proposed

Added warning "No Events found" when there are no events.

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Screenshots

Capture

### CODE REVIEW

**Review by accodes21 — COMMENTED** [review]
Looks good

File: components/user/UserEvents.js [hunk 1]
```diff
@@ -74,21 +74,23 @@ export default function UserEvents({
 
   return (
     <>
-      {eventsToShow.length === 0 && !manage && (
+      {eventsToShow.length === 0 && manage && (
```
Comment (eddiejaoude) [inline components/user/UserEvents.js:77]: Now it won't show on the user's profile? This will create another bug

File: components/user/UserEvents.js [hunk 2]
```diff
@@ -74,21 +74,23 @@ export default function UserEvents({
...
-        value={eventType}
-        label="Select an event type"
-        onChange={handleEventTypeChange}
-        options={filteredEventOptions.map((option) => ({
-          label: option.name,
-          value: option.value,
-        }))}
-        className="inline text-center text-sm font-medium leading-6 text-primary-high sm:pt-1.5"
-      />
+      {eventsToShow.length > 0 && manage && (
```
Comment (eddiejaoude) [inline components/user/UserEvents.js:81]: This will break on the user's profile

**Review by eddiejaoude — CHANGES_REQUESTED** [review]
Thank you for your contribution 👍 

The component is used in multiple places, the changes will create bugs in other places it is used

**Comment by eddiejaoude** [comment]
> Looks good

@accodes21 please do not approve pull requests without reviewing properly, this causes noise and confusing to the contributor and the maintainers

**Review by eddiejaoude — APPROVED** [review]
Thank you 👍
