### PR TITLE
Fixes Issue:  #8533 [BUG] The order of pinned icons doesn't change

### LINKED ISSUE #8533: [BUG] The order of pinned icons doesn't change.
### Description

After ordering the links, the order of pinned links doesn't change; it remains the same.

Social shortcut icons should be ordered by the links order

Screenshot 2023-08-07 at 10 02 59

### Screenshots

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by mianakbarjan**
## Fixes Issue #8533 

Closes #8533  -->

## Check List (Check all the applicable boxes) 

- [X] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [X] All new and existing tests passed.
- [X] This PR does not contain plagiarized content.
- [X] The title of my pull request is a short description of the requested changes.

### CODE REVIEW

File: pages/api/profiles/[username]/index.js [hunk 1]
```diff
@@ -114,6 +114,9 @@ export async function getUserApi(req, res, username, options = {}) {
       ),
     socials: getProfile.links
       .filter((link) => link.isPinned)
+      .sort(
+        (a, b) => (a.order ?? Number.MAX_VALUE) - (b.order ?? Number.MAX_VALUE),
```
Comment (sital002) [inline pages/api/profiles/[username]/index.js:118]: Is this ```?? Number.MAX_VALUE``` really required can you please explain what edge case does it handle.

Comment (mianakbarjan) [reply pages/api/profiles/[username]/index.js:118]: `Number.MAX_VALUE` is used in case a.order or b.order values are null or undefined. You can see the same method used for the enabled links part right above this code.

Comment (eddiejaoude) [reply pages/api/profiles/[username]/index.js:118]: Great collaboration 👍

**Review by eddiejaoude — APPROVED** [review]
Thank you for the contribution 👍
