### PR TITLE
fix: disable the reorder button unless there is more than one link added

### LINKED ISSUE #9221: [BUG] Reorder button should be visible only if multiple links added
### Description

Edit:
~~We can hide~~ `Disable` the reorder button unless there is more than one link added.

### Screenshots

reorder

### Do you want to work on this issue?

Yes

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by sanketmp**
## Fixes Issue
Fixes #9221 

## Changes proposed
- Added condition to disable/enable the reorder button depending on number of links added.

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Screenshots
https://github.com/EddieHubCommunity/BioDrop/assets/68698332/5b7eff77-7c92-4b2c-a24a-800559e962ff

## Note to reviewers
_(attached video instead of screenshot)_

### CODE REVIEW

File: pages/account/manage/links.js [hunk 1]
```diff
@@ -112,7 +112,7 @@ export default function ManageLinks({ BASE_URL, username, links }) {
           </Button>
 
           {linkList.length !== 0 && !reorder && (
-            <Button onClick={() => setReorder(true)}>
+            <Button onClick={() => setReorder(true)} disable={linkList.length < 2}>
```
Comment (hi-Kartik2004) [inline pages/account/manage/links.js:115]: Maybe you could add `disabled` to the reorder button on the disable condition, so that it's easier to figure out that the reorder button is disabled, along with making the pointer events to be none.

Refer the below syntax for details

```
     <button type="button" className="some tailwind classes" disabled>Button</button>
```

### This is how the disabled button will look after the change (ofcourse, pointer events will still remain none)
image

Comment (sanketmp) [reply pages/account/manage/links.js:115]: Button is a custom component defined in `components/Button.js` which is imported in `manage/links.js` and `disable` is a prop not html attribute.
And using `disabled` directly on `<button> in components/Button.js` will not check condition.

Comment (eddiejaoude) [inline pages/account/manage/links.js:115]: From the line above, I think we need to remove this so it is displayed? `linkList.length !== 0`

Comment (sanketmp) [reply pages/account/manage/links.js:115]: `linkList.length !== 0` is for displaying/hiding reorder button. if we removed that, it will display _disabled_ reorder button even if there are no links. 

`linkList.length !== 0`will check if any links are there  and  `disable={linkList.length < 2}`will check how many and then disable/enable. So we need both.

Comment (eddiejaoude) [reply pages/account/manage/links.js:115]: Yes you discussed this with our maintainer here https://github.com/EddieHubCommunity/BioDrop/issues/9221#issuecomment-1742009718

Comment (sanketmp) [reply pages/account/manage/links.js:115]: okay and will do the changes.

**Review by eddiejaoude — APPROVED** [review]
Thank you 👍
