### PR TITLE
Fix: added margin to manage link page

### LINKED ISSUE #8774: [BUG] Add more space between link container and button container on Manage Links Page
### Description

i think we could add more margin between the `add link` button row and the `available link` row. the edit button looks like "touching" the add link button

### Screenshots

image

### Additional information

if this issue got approved. i'd love to be the one working on this

### PR DESCRIPTION
**Pull request by khairnsaa**
## Fixes Issue
Closes #8774

## Changes proposed
added 12 px of margin bottom for each button on manage links, milestone, events, and repos page
`<div className="flex gap-4 mb-3">`

i also made a little change on `components/user/userRepos.jsx` to add margin between user repos component, because the icon looks "touching" previous component. here's the result of this changes.

## Check List (Check all the applicable boxes) 

- [X] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [X] This PR does not contain plagiarized content.
- [X] The title of my pull request is a short description of the requested changes.

## Screenshots

result of the changes:
image

before the change on `components/user/userRepos.jsx`:
image

after the changes on `components/user/userRepos.jsx`:
image

### CODE REVIEW

File: pages/account/manage/events.js [hunk 1]
```diff
@@ -71,7 +71,7 @@ export default function ManageEvents({ events }) {
         )}
 
         <Navigation />
-        <Button href="/account/manage/event">
+        <Button href="/account/manage/event" style={{"margin-bottom": "12px"}}>
```
Comment (eddiejaoude) [inline pages/account/manage/events.js:74]: Please use tailwind classes

**Review by eddiejaoude — CHANGES_REQUESTED** [review]
Thank you for the contribution 👍 

I have added inline comments. Could the styling be consistently added to all manage pages?

File: pages/account/manage/events.js (hunk 1 above)
Comment (khairnsaa) [reply pages/account/manage/events.js:74]: Hi eddie!

for that line of code i didn't use tailwind classes because when i used it it will override the default classes from `Button` component, and the button will look like this
image

that's why i'm using the style props

Comment (khairnsaa) [reply pages/account/manage/events.js:74]: Should i add a new props? Like whether the button used for manage pages or not. 
Or maybe just add the margin to the button component?

Comment (eddiejaoude) [reply pages/account/manage/events.js]: Thank you for making the changes. I think in most places it looks ok, on the map page the button is a bit off but I don't think a blocker

Screenshot 2023-09-01 at 10 18 52

**Review by eddiejaoude — APPROVED** [review]
Thank you 👍
