### PR TITLE
Fix: 8824 Edit Icon Alignment fix in the links page.

### LINKED ISSUE #8824: [FEATURE] Edit button on manage links page looks out of place
### Description

On the links page, we have the edit button over the button itself, and it's covering the icon such that it looks a little bit weird. Is there no way to shift the edit circle? Maybe put it at the end of the link button, or within it like the milestone page?

### Screenshots

Screenshot (182)

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by hi-Kartik2004**
## Fixes Issue

Closes #8824

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

### How it will look after merging this PR
image

### How it looks now
image

## Note to reviewers
This modification **does not impact** other pages using the Edit component as the component now accepts a new prop i.e className for modifications instead of changing the exisiting classes.

### CODE REVIEW

**Comment by SaraJaoude** [comment]
Please take into consideration the comments [here](https://github.com/EddieHubCommunity/BioDrop/issues/8824#issuecomment-1940867511).

File: components/user/UserLink.js [hunk 1]
```diff
@@ -92,17 +94,18 @@ export default function UserLink({
         </span>
       )}
       {manage && <Bulb isEnabled={isEnabled} />}
+      </div>
     </Link>
   );
 
   const edit = (link) => (
-    <Edit href={`/account/manage/link/${link._id}`} label={`${link.name} Link`}>
+    <Edit className={"mt-5 ml-4"} href={`/account/manage/link/${link._id}`} label={`${link.name} Link`}>
```
Comment (luismr00) [inline components/user/UserLink.js:102]: Could've just put the classname styles into the Edit component instead of passing them as props. Works the same either way.

**Review by luismr00 — APPROVED** [review]

File: components/account/manage/Edit.js [hunk 2]
```diff
@@ -1,12 +1,12 @@
...
 
-export default function Edit({ href, label = "", children }) {
+export default function Edit({ href, label = "", children, className }) {
   return (
     <div className="relative w-full">
       <a
         href={href}
         aria-label={`Edit ${label}`}
-        className="rounded-full bg-secondary-medium p-2 mt-1 text-white shadow-sm hover:bg-tertiary-medium focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-secondary-medium absolute top-0 left-0 pointer z-10"
+        className={`rounded-full bg-secondary-medium p-2 mt-1 text-white shadow-sm hover:bg-tertiary-medium focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-secondary-medium absolute top-0 left-0 pointer z-10 ${className}`}
```
[the remark this answers is not in the document]
Comment (hi-Kartik2004) [reply components/account/manage/Edit.js:9]: You are right Thomas, although it wouldn't effect the functionality, its indeed better to initialise the className to empty string by default.

Done this change :)

File: components/user/UserLink.js (hunk 1 above)
Comment (hi-Kartik2004) [reply components/user/UserLink.js:102]: Nope it did not, I tried doing this in the first place however it impacted other places where the Edit component is used, as a result I decided to pass the classNames as props for this case, so they don't impact other places.

Comment (luismr00) [reply components/user/UserLink.js:102]: Ah, ok. Wasn't aware. Will vouch with an approval then.

**Review by luismr00 — APPROVED** [review]

**Review by eddiejaoude — APPROVED** [review]
Great collaboration 👍
