### PR TITLE
fix:multiple re-render in profile page

### LINKED ISSUE #9368: [BUG] profile page is rendering twice
### Description

Steps to reproduce:
Go to https://www.biodrop.io/eddiejaoude
When going from the links tab to other tabs the page renders twice. You can see a flicker when you change the tab from links to other tabs. 

### Screenshots

_No response_

### Do you want to work on this issue?

Yes

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by sital002**
## Fixes Issue

closes #9368 

## Changes proposed
Refactor the UserTabs component and added ```shallow:true``` which will prevent re-running ```getServerSideProps```

## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

### CODE REVIEW

**Review by eddiejaoude — CHANGES_REQUESTED** [review]
Thank you for the contribution Sital, but I get this error in your branch  

Screenshot 2023-10-07 at 05 28 36

**Comment by sital002** [comment]
I added a props for ```Tabs``` component but I forgot to add it in the ```manage/profile``` page. Let me fix that

**Comment by sital002** [comment]
I think we need to update the test for the profile page since I used a button instead of a link in the ```Tabs``` component the test should be changed accordingly.

File: components/navbar/SubNav.js [hunk 1]
```diff
@@ -1,21 +1,18 @@
-import Router, { useRouter } from "next/router";
+import { useRouter } from "next/router";
 import Tabs from "@components/Tabs";
+import { usePathname } from "next/navigation";
```
Comment (dan-mba) [inline components/navbar/SubNav.js:3]: `next/navigation` is for use only with the `app` directory.
Since we use the `pages` directory, `router.pathname` should be used.

File: components/user/themes/UserTabs.js [hunk 2]
```diff
@@ -1,6 +1,4 @@
-import { useState } from "react";
-import { usePathname, useSearchParams } from "next/navigation";
-
+import { useSearchParams } from "next/navigation";
```
Comment (dan-mba) [inline components/user/themes/UserTabs.js:1]: `next/navigation` is for use only with the `app` directory.
Since we use the `pages` directory, `router.query` should be used.

File: components/navbar/SubNav.js (hunk 1 above)
Comment (eddiejaoude) [reply components/navbar/SubNav.js]: oh good spot 👍

**Review by eddiejaoude — APPROVED** [review]
Looks great 👍
